### ISSUE TITLE
Rest endpoint to get SKU entities fails

### ISSUE THREAD

**Issue by vbouchet31** [acquia/commerce-manager#75]
When enabling the default GET endpoint to fetch SKU entities, any GET request fails due to non-existing  "entity.acq_sku_type.canonical" route.

I simply added the following code in sku.routing.yml and it started working as expected:
```
entity.sku_type.canonical:
  path: '/admin/commerce/config/sku/{acq_sku_type}'
  defaults:
    _entity_form: 'sku_type.edit'
  requirements:
    _permission: 'administer commerce sku entity'
```

I have not created a PR yet because I suspect it also needs change in links.action|menu|task.yml to be proper fix.
